version: "3.9"

services:
  attendance:
    build:
      context: ./attendance
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    env_file:
      - ./attendance/.env
    volumes:
      - ./attendance/secrets:/app/secrets:ro
    restart: unless-stopped
  auth:
    build:
      context: ./fastapi-oauth
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./fastapi-oauth/.env
    volumes:
      - ./fastapi-oauth/secrets:/app/secrets:ro
    restart: unless-stopped
